pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    dockerImage = docker.build("vcard-portfolio")
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                // Add any test commands here
            }
        }
        stage('Deploy') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-credentials') {
                        dockerImage.push("latest")
                    }
                    sh 'docker run -d -p 80:80 vcard-portfolio:latest'
                }
            }
        }
    }
}
